//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Rol { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}
