//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Correo
    {
        public int Id_Correo { get; set; }
        [DisplayName("Correo")]
        public string Correo1 { get; set; }
        public Nullable<int> Contacto { get; set; }
    
        public virtual Contacto Contacto1 { get; set; }
    }
}
