//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Contacto = new HashSet<Contacto>();
            this.EstadodeCuenta = new HashSet<EstadodeCuenta>();
            this.Marketing = new HashSet<Marketing>();
            this.Publicidad = new HashSet<Publicidad>();
            this.Recordatorio = new HashSet<Recordatorio>();
            this.ServicioEmpresa = new HashSet<ServicioEmpresa>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id_Empresa { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Cedula { get; set; }
        public string Pais { get; set; }
        [DisplayName("Provincia")]
        public Nullable<int> Id_Provincia { get; set; }
        [DisplayName("Canton")]
        public Nullable<int> Id_Canton { get; set; }
        public Nullable<int> Id_Distrito { get; set; }
        [DisplayName("Otras señas")]
        public string Otras_Señas { get; set; }
        [DisplayName("Codigo Postal")]
        public int Codigo_Postal { get; set; }
    
        public virtual Canton Canton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadodeCuenta> EstadodeCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketing> Marketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicidad> Publicidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recordatorio> Recordatorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioEmpresa> ServicioEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
