//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ServicioEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicioEmpresa()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }

        public int Id_Servicio_Empresa { get; set; }
        public int Id_Producto { get; set; }
        public string Descripcion { get; set; }
        [DisplayName("Fecha de Creacion")]
        public System.DateTime Fecha_Creacion { get; set; }
        [DisplayName("Primer Pago")]
        public Nullable<System.DateTime> Primer_Pago { get; set; }
        public System.DateTime Renovacion { get; set; }
        public int Empresa { get; set; }
        public double Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
